openapi: "3.0.2"
info:
  title: Swagger Todo App - OpenAPI 3.0
  description:
    Simple Todo App Server based on the OpenAPI 3.0 specification. You can find out more about
    Swagger at [https://swagger.io](https://swagger.io).


    Useful links

    - [Todo App repository](https://github.com/SamuelJAmos/todo-openapi-spec)

    - [The source API definition for the Todo App](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
    # Example links above. Change to match/use as inspo on useful context keeping.
  termsOfService: http://swagger.io/terms/
  # Example TOS page.
  # !!! THIS WILL NEED TO BE CHANGED !!!
  contact:
    email: Samuelamos@icloud.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
    # Why is this needed?
    # Is it needed???
  version: "1.0"
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
  # Change to the proper docs URL
  # Will host the stuff from figma like the user flows and glossary/definitions
servers:
  - url: https://api.server.todo/v1
  # Change URL for the CORRECT server URL 
paths:
  /test:
    get:
      responses:
        "200":
          description: OK
